package com.gavinflood.lists.api.domain

import javax.persistence.*

/**
 * An abstract base entity that other entities should extend from if they need an autogenerated primary key.
 */
@MappedSuperclass
abstract class BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    val id: Long = 0

}