package com.gavinflood.lists.api.domain

import java.util.*
import javax.persistence.*

/**
 * An abstract base entity that other entities should extend from if they need an autogenerated primary key.
 */
@MappedSuperclass
abstract class BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    val id: Long = 0

    @Column(name = "created_date")
    val createdDate = Date()

    @Column(name = "retired")
    var retired = false

    @Column(name = "retired_date")
    var retiredDate: Date? = null

    /**
     * Retire the row.
     */
    fun retire() {
        retired = true
        retiredDate = Date()
    }

}